name: CI
on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: Debbl/game.aiwan.run
          exclude_assets: ".github,.nojekyll"
          publish_branch: main
          publish_dir: dist
          destination_dir: pages/bubble-wrap
